name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      TURBO_UI: "0"
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - name: Format
        run: pnpm format:check

      - name: Lint
        run: pnpm lint

      - name: Type check
        run: pnpm turbo typecheck

      - name: Test with coverage
        run: pnpm turbo test:coverage

      - name: Build
        run: pnpm build
        env:
          POSTGRES_URL: "postgresql://fake:fake@localhost:5432/fake"
          REDIS_URL: "redis://localhost:6379"
